[project]
name = "odoo-addons-sygel-technology-sy-server-tools"
version = "18.0.20260603.0"
dependencies = [
    "odoo-addon-base_confirmation_requirement_rules==18.0.*",
    "odoo-addon-html_fields_document_layout_configuration==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
